### PR TITLE
Task #182: Add responsivity to PoM dApp

### PR DESCRIPTION
**Pull request by amandaalexandre**
Solves issue: https://tree.taiga.io/project/yulkor-developing-pom/us/182

This PR consists of:
- Added .5 rem margin to the red alert model;
- Remove width constraint to the h1 element and the input form in smaller screens
- Added column orientation to the form flexbox container

Still haven't checked how the membership page looks with several membership cards.

Prints:
image

image

### CODE REVIEW

**Review by tracyspacy — CHANGES_REQUESTED** [review]
Hi, there are 3 small things requiring fixing:
1. on the main page 5 recent communities layout should be fixed for mobile - see pic fix1
fix1
2. on the screen RegisterNameFinal info field's width should be fixed, if admin address is loaded it breaks layout, if there is "loading" state layout works. see pics fix2-1, fix2-2
fix2-1
fix2-2

**Comment by amandaalexandre** [comment]
Fix Issue 1 by setting the recent communities tab to display vertically on smaller screens:
Captura de tela de 2024-01-11 01-44-45

**Comment by amandaalexandre** [comment]
Captura de tela de 2024-01-11 02-28-21
Fixed the overflow of the wrapping admin string and the image became responsive with a maximum of 20rem, as set before.

**Review by tracyspacy — APPROVED** [review]
thx, all good!

**Pull request merged**
